version: "3.1"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - nextjs
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/certificates:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: always
    # ports:
    #   - "3000:3000"

  twitch_db:
    image: postgres
    container_name: twitch_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: twitch
    volumes:
      - twitch_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  twitch_adminer:
    image: adminer
    container_name: twitch_adminer
    restart: always
    ports:
      - 8080:8080

  twitch_redis:
    image: redislabs/redismod
    container_name: twitch_redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/db

  twitch_redisinsight:
    image: oblakstudio/redisinsight
    container_name: twitch_redisinsight
    restart: always
    ports:
      - "8006:5540"
    volumes:
      - redis_db:/db

volumes:
  twitch_data:
  redis_db:
