services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs:1.0.0
    expose:
      - "3000"
    depends_on:
      - twitch_db
      - twitch_redis
    deploy:
      replicas: 1
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3000"

  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - '81:81'
    env_file:
      - .env
    volumes:
      - nginx_proxy_manager_data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb_aria

  mariadb_aria:
    image: 'jc21/mariadb-aria'
    container_name: mariadb_aria
    restart: unless-stopped
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - mariadb_db:/var/lib/mysql
    ports:
      - '3307:3306'

  twitch_db:
    image: postgres
    container_name: twitch_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: twitch
    volumes:
      - twitch_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  twitch_redis:
    image: redislabs/redismod
    container_name: twitch_redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/db

volumes:
  twitch_data:
  redis_db:
  mariadb_db:
  nginx_proxy_manager_data:
