services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs:1.0.0
    expose:
      - "3000"
    depends_on:
      - twitch_db
      - twitch_redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`localhost`)"
      - "traefik.http.routers.nextjs.entrypoints=http"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    networks:
      - traefik_network
    deploy:
      replicas: 1
    environment:
      - NODE_ENV=production
    restart: always

  twitch_db:
    image: postgres:alpine
    container_name: twitch_db
    networks:
      - traefik_network
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: twitch
    volumes:
      - twitch_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  twitch_redis:
    image: redis:alpine
    container_name: twitch_redis
    networks:
      - traefik_network
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/db

volumes:
  twitch_data:
  redis_db:

networks:
  traefik_network:
    external: true
