services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - nextjs_app_1
      - nextjs_app_2
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      # - ./nginx/certificates:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always

  nextjs_app_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app_1
    expose:
      - "3000"
    depends_on:
      - twitch_db
      - twitch_redis
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3001:3000"

  nextjs_app_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app_2
    expose:
      - "3000"
    depends_on:
      - twitch_db
      - twitch_redis
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3002:3000"

  twitch_db:
    image: postgres
    container_name: twitch_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: twitch
    volumes:
      - twitch_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  twitch_redis:
    image: redislabs/redismod
    container_name: twitch_redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/db

volumes:
  twitch_data:
  redis_db:
