services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs:1.0.0
    expose:
      - "3000"
    depends_on:
      - twitch_db
      - twitch_redis
    deploy:
      replicas: 1
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "3000:3000"

  twitch_db:
    image: postgres:alpine
    container_name: twitch_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: twitch
    volumes:
      - twitch_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  twitch_redis:
    image: redis:alpine
    container_name: twitch_redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/db

volumes:
  twitch_data:
  redis_db:
