services:
  twitch_redisinsight:
    image: oblakstudio/redisinsight
    container_name: twitch_redisinsight
    restart: always
    ports:
      - "8006:5540"
    volumes:
      - redis_db:/db

  twitch_adminer:
    image: adminer
    container_name: twitch_adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis_db:
