filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/logs/graphql-default-*.log
    json:
      keys_under_root: true
      overwrite_keys: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
