services:
  twitch_db:
    image: postgres:alpine
    container_name: twitch_db
    networks:
      - twitch_network
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: twitch
    volumes:
      - twitch_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  twitch_redis:
    image: redis:alpine
    container_name: twitch_redis
    networks:
      - twitch_network
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_db:/db

volumes:
  twitch_data:
  redis_db:

networks:
  twitch_network:
    name: twitch_network
    driver: bridge
